slack_url: https://hooks.slack.com/services/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
rounds: 10
buttons:
  - colour: red
    text_colour: black
    text: GREEN
    url: https://i.imgur.com/3OJS3N3.jpg?1
  - colour: green
    text_colour: black
    text: GREEN
    url: https://i.imgur.com/3OJS3N3.jpg?1
  - colour: blue
    text_colour: black
    text: GREEN
    url: https://i.imgur.com/3OJS3N3.jpg?1
  - colour: yellow
    text_colour: black
    text: GREEN
    url: https://i.imgur.com/3OJS3N3.jpg?1
  - colour: orange
    text_colour: black
    text: GREEN
    url: https://i.imgur.com/3OJS3N3.jpg?1
